import React, { useState } from 'react';
import { ChevronRight, Loader2, Sparkles } from 'lucide-react';
import { LanguageCode } from '../types/database';
import { StarterDeck, getStarterDecksForLanguage } from '../data/starterDecks';
import { StarterWord, generateStarterDeck } from '../lib/aiClient';
import { getLanguageMeta } from '../lib/languageHelper';
import { Button, Field, Notice, Segmented, inputClass } from './ui';

type Level = 'beginner' | 'elementary' | 'intermediate';
const LEVEL_LABEL: Record<Level, string> = { beginner: '입문', elementary: '초급', intermediate: '중급' };

interface StarterDeckPickerProps {
  language: LanguageCode;
  onImportDeck: (deck: StarterDeck) => void;
  onImportGenerated: (title: string, words: StarterWord[]) => void;
}

/**
 * Starter word lists for the learner's language only.
 * Built-in decks exist for 영어·일본어·히브리어·헬라어; every other language can
 * get one generated by AI (same language only, reviewed before saving).
 */
export const StarterDeckPicker: React.FC<StarterDeckPickerProps> = ({ language, onImportDeck, onImportGenerated }) => {
  const lang = getLanguageMeta(language);
  const decks = getStarterDecksForLanguage(language);
  const canGenerate = language !== 'other' && language !== 'ko';
  const [level, setLevel] = useState<Level>('beginner');
  const [topic, setTopic] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [preview, setPreview] = useState<StarterWord[] | null>(null);

  const generate = async () => {
    setBusy(true);
    setError(null);
    const res = await generateStarterDeck(language, level, topic.trim(), 30);
    setBusy(false);
    if (!res.ok) setError(res.error);
    else setPreview(res.data);
  };

  return (
    <div className="space-y-2">
      {decks.map(deck => (
        <button
          key={deck.id}
          onClick={() => onImportDeck(deck)}
          className="w-full flex items-center justify-between gap-3 px-4 py-3 rounded-xl border border-line bg-surface hover:border-line-strong text-left"
        >
          <span className="min-w-0">
            <span className="block text-[15px] font-medium">{deck.title}</span>
            <span className="block text-[13px] text-muted">
              {deck.description} · {deck.items.length}단어
            </span>
          </span>
          <ChevronRight className="w-4 h-4 text-muted shrink-0" />
        </button>
      ))}

      {canGenerate && !preview && (
        <div className="rounded-xl border border-line bg-surface p-4">
          <p className="text-[15px] font-medium flex items-center gap-1.5">
            <Sparkles className="w-4 h-4 text-accent" /> AI로 {lang.name} 기본 단어장 만들기
          </p>
          <p className="text-[13px] text-muted mt-1">자주 쓰는 {lang.name} 단어 30개를 수준에 맞춰 골라 드립니다.</p>
          <div className="mt-3 space-y-3">
            <Segmented<Level>
              size="sm"
              value={level}
              onChange={setLevel}
              options={(Object.keys(LEVEL_LABEL) as Level[]).map(l => ({ value: l, label: LEVEL_LABEL[l] }))}
            />
            <Field label="주제 (선택)">
              <input className={inputClass} value={topic} onChange={e => setTopic(e.target.value)} placeholder="예: 여행, 음식, 성경" maxLength={40} />
            </Field>
            <Button block onClick={generate} disabled={busy}>
              {busy ? <Loader2 className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
              {busy ? '만드는 중…' : '단어장 만들기'}
            </Button>
          </div>
        </div>
      )}

      {preview && (
        <div className="rounded-xl border border-line bg-surface p-4">
          <p className="text-[15px] font-medium">
            {lang.name} {LEVEL_LABEL[level]}
            {topic.trim() ? ` · ${topic.trim()}` : ''} · {preview.length}단어
          </p>
          <p className="text-[13px] text-ink-2 mt-2 leading-relaxed">
            {preview
              .slice(0, 8)
              .map(w => `${w.term} (${w.meaning})`)
              .join(', ')}
            {preview.length > 8 ? ' …' : ''}
          </p>
          <div className="grid grid-cols-2 gap-2 mt-3">
            <Button onClick={() => setPreview(null)}>다시 만들기</Button>
            <Button
              variant="primary"
              onClick={() =>
                onImportGenerated(`${lang.name} ${LEVEL_LABEL[level]}${topic.trim() ? ` · ${topic.trim()}` : ''} 기본 단어`, preview)
              }
            >
              불러오기
            </Button>
          </div>
        </div>
      )}

      {error && <Notice tone="bad">{error}</Notice>}
      {decks.length === 0 && !canGenerate && (
        <p className="text-[14px] text-ink-2">이 언어는 기본 단어장이 없습니다. 단어를 직접 추가해 주세요.</p>
      )}
    </div>
  );
};
